[package]
name = "abc163"
version = "0.1.0"
authors = ["FirstSS-Sub <sota.monokuma.bass.1@gmail.com>"]
edition = "2018"

# dependencies added to new project
[dependencies]
proconio = "*"

[profile.release]
lto = true
panic = 'abort'
